<?php

global $_FIELD_MAPPING_;

$_FIELD_MAPPING_ = array(
	 "_transaction_date_from" 							=> "transaction_date_from"
	,"_transaction_date_to" 							=> "transaction_date_to"
	,"_transaction_created_from" 						=> "transaction_created_from"
	,"_transaction_created_to" 							=> "transaction_created_to"
	,"_transaction_updated_from" 						=> "transaction_updated_from"
	,"_transaction_updated_to" 							=> "transaction_updated_to"
	,"_process_transaction_date_csv" 					=> "process_transaction_date_csv"
	,"_process_source_transaction_host_csv" 			=> "process_source_transaction_host_csv"
	,"_process_source_transaction_host_instance_csv" 	=> "process_source_transaction_host_instance_csv"
	,"_process_source_transaction_type_csv" 			=> "process_source_transaction_type_csv"
	,"_process_source_transaction_id_csv" 				=> "process_source_transaction_id_csv"
	,"_process_source_transaction_title_csv" 			=> "process_source_transaction_title_csv"
	,"_process_source_transaction_status_csv" 			=> "process_source_transaction_status_csv"
	,"_process_source_location_type_csv" 				=> "process_source_location_type_csv"
	,"_process_source_location_csv"						=> "process_source_location_csv"
	,"_process_target_transaction_host_csv" 			=> "process_target_transaction_host_csv"
	,"_process_target_transaction_host_instance_csv" 	=> "process_target_transaction_host_instance_csv"
	,"_process_target_transaction_type_csv" 			=> "process_target_transaction_type_csv"
	,"_process_target_transaction_id_csv" 				=> "process_target_transaction_id_csv"
	,"_process_target_transaction_title_csv" 			=> "process_target_transaction_title_csv"
	,"_process_target_transaction_status_csv" 			=> "process_target_transaction_status_csv"
	,"_process_target_location_type_csv" 				=> "process_target_location_type_csv"
	,"_process_target_location_csv" 					=> "process_target_location_csv"
	,"_ignore_transaction_date_csv" 					=> "ignore_transaction_date_csv"
	,"_ignore_source_transaction_host_csv" 				=> "ignore_source_transaction_host_csv"
	,"_ignore_source_transaction_host_instance_csv" 	=> "ignore_source_transaction_host_instance_csv"
	,"_ignore_source_transaction_type_csv" 				=> "ignore_source_transaction_type_csv"
	,"_ignore_source_transaction_id_csv" 				=> "ignore_source_transaction_id_csv"
	,"_ignore_source_transaction_title_csv" 			=> "ignore_source_transaction_title_csv"
	,"_ignore_source_transaction_status_csv" 			=> "ignore_source_transaction_status_csv"
	,"_ignore_source_location_type_csv"					=> "ignore_source_location_type_csv"
	,"_ignore_source_location_csv" 						=> "ignore_source_location_csv"
	,"_ignore_target_transaction_host_csv" 				=> "ignore_target_transaction_host_csv"
	,"_ignore_target_transaction_host_instance_csv" 	=> "ignore_target_transaction_host_instance_csv"
	,"_ignore_target_transaction_type_csv" 				=> "ignore_target_transaction_type_csv"
	,"_ignore_target_transaction_id_csv" 				=> "ignore_target_transaction_id_csv"
	,"_ignore_target_transaction_title_csv" 			=> "ignore_target_transaction_title_csv"
	,"_ignore_target_transaction_status_csv" 			=> "ignore_target_transaction_status_csv"
	,"_ignore_target_location_type_csv" 				=> "ignore_target_location_type_csv"
	,"_ignore_target_location_csv" 						=> "ignore_target_location_csv"
	,"_integration_atomic_by_day" 						=> "integration_atomic_by_day"
	,"_integration_status_outstanding" 					=> "integration_status_outstanding"
	,"_integration_retry_partials" 						=> "integration_retry_partials"
);
