<?php

//define("_API_GET_SORT_INDEX_URL_", "https://dev.playbill.com.au/api/v1/products/sort_index/");

global $_GET_FIELD_MAPPING_;
global $_POST_FIELD_MAPPING_;
global $_DELETE_FIELD_MAPPING_;

$_GET_FIELD_MAPPING_ = array(
	 "_id"								=>	"id"
	,"_hash"							=>	"hash"
	,"_sku"								=>	"sku"
	,"_barcode"							=>	"barcode"
	,"_company"							=>	"company"
	,"_country_code"					=>	"country_code"
	,"_region"							=>	"region"
	,"_search"							=>	"search"
	,"_order_by"						=>	"order_by"
	,"_asc"								=>	"asc"
);

$_POST_FIELD_MAPPING_ = array(
	 "_product_id"						=>	"id"
	,"_sku"								=>	"sku"
	,"_barcode"							=>	"barcode"
	,"_company"							=>	"company"
	,"_country_code"					=>	"country_code"
	,"_hierarchy_id"					=>	"hierarchy_id"
	,"_hierarchy_code"					=>	"hierarchy_code"
	,"_hierarchy_title"					=>	"hierarchy_title"
	,"_name"							=>	"name"
	,"_brand"							=>	"brand"
	,"_category"						=>	"category"
	,"_type"							=>	"type"
	,"_costing_method"					=>	"costing_method"
	,"_uom"								=>	"uom"
	,"_retail_price"					=>	"retail_price"
	,"_last_cost_price"					=>	"last_cost_price"
	,"_fixed_cost_price"				=>	"fixed_cost_price"
	,"_average_cost_price"				=>	"average_cost_price"
	,"_wholesale_price"					=>	"wholesale_price"
	,"_last_supplied_by"				=>	"last_supplied_by"
	,"_supplier_product_code"			=>	"supplier_product_code"
	,"_supplier_product_name"			=>	"supplier_product_name"
	,"_category_tier_1"					=>	"category_tier_1"
	,"_category_tier_2"					=>	"category_tier_2"
	,"_category_tier_3"					=>	"category_tier_3"
	,"_category_tier_4"					=>	"category_tier_4"
	,"_category_tier_5"					=>	"category_tier_5"
	,"_category_tier_6"					=>	"category_tier_6"
	,"_category_tier_7"					=>	"category_tier_7"
	,"_category_tier_8"					=>	"category_tier_8"
	,"_category_tier_9"					=>	"category_tier_9"
	,"_category_tier_10"				=>	"category_tier_10"
	,"_year"							=>	"year"
	,"_season"							=>	"season"
	,"_business_stream"					=>	"business_stream"
	,"_department"						=>	"department"
	,"_variant_1_name"					=>	"variant_1_name"
	,"_variant_1_value"					=>	"variant_1_value"
	,"_variant_2_name"					=>	"variant_2_name"
	,"_variant_2_value"					=>	"variant_2_value"
	,"_variant_3_name"					=>	"variant_3_name"
	,"_variant_3_value"					=>	"variant_3_value"
	,"_variant_4_name"					=>	"variant_4_name"
	,"_variant_4_value"					=>	"variant_4_value"
	,"_variant_5_name"					=>	"variant_5_name"
	,"_variant_5_value"					=>	"variant_5_value"
	,"_stock_locator"					=>	"stock_locator"
	,"_length"							=>	"length"
	,"_width"							=>	"width"
	,"_height"							=>	"height"
	,"_weight"							=>	"weight"
	,"_hs_code"							=>	"hs_code"
	,"_region"							=>	"region"
	,"_financial_grouping_code"			=>	"financial_grouping_code"
	,"_financial_expense_account"		=>	"financial_expense_account"
	,"_financial_revenue_account"		=>	"financial_revenue_account"
	,"_financial_inventory_account"		=>	"financial_inventory_account"
	,"_financial_cogs_account"			=>	"financial_cogs_account"
	,"_financial_liability_account"		=>	"financial_liability_account"
	,"_financial_purchase_tax_account"	=>	"financial_purchase_tax_account"
	,"_financial_sale_tax_account"		=>	"financial_sale_tax_account"
	,"_taxable"							=>	"taxable"
	,"_licensed"						=>	"licensed"
	,"_charitable"						=>	"charitable"
	,"_free"							=>	"free"
	,"_consignment"						=>	"consignment"
	,"_sorting_index"					=>	"sorting_index"
	,"_description"						=>	"description"
	,"_tags"							=>	"tags"
	,"_status"							=>	"status"
);

$_DELETE_FIELD_MAPPING_ = array(
	 "_product_id"						=>	"id"
	,"_sku"								=>	"sku"
	,"_barcode"							=>	"barcode"
	,"_company"							=>	"company"
	,"_country_code"					=>	"country_code"
);
